ratings:
  namespace: student19-bookinfo-uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  image: ghcr.io/patipolzaza/bookinfo-ratings
  tag: uat
ingress:
  host: sitkmutt.bookinfo.uat.opsta.net
  path: "/student19/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-uat-ratings-mongodb:27017/ratings
  MONGO_DB_USERNAME: ratings
  COMMIT_SHA: CHANGEME
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-uat-ratings-mongodb-secret: mongodb-password